function [ys_, params, info] = nobond_noadj_linear_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(11)=0;
    ys_(10)=0;
    kovern=0;
    covern=0;
    ys_(6)=0;
    G=0;
    ys_(3)=0;
    ys_(2)=0;
    ys_(1)=0;
    ys_(5)=0;
    ys_(4)=0;
    ys_(8)=0;
    ys_(9)=0;
    ys_(7)=0;
    yovern=0;
    % Auxiliary equations
    check_=0;
end
