function [ys_, params, info] = nobond_noadj_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(12)=params(17);
    ys_(11)=params(16);
    kovern=ys_(12)^(1/(params(4)-1));
    covern=kovern^params(4)-kovern*params(5);
    ys_(6)=1-(ys_(12)+params(1)*(1-params(5))-1)/(ys_(12)*(1-params(4)*params(1)));
    G=kovern^params(4)*(1-ys_(6))*(1-params(4))/(covern*params(3));
    ys_(3)=G/(1+G);
    ys_(2)=covern*ys_(3);
    ys_(1)=params(3)*ys_(2)/(1-ys_(3));
    ys_(5)=kovern*ys_(3);
    ys_(4)=ys_(2)-ys_(3)*ys_(1);
    ys_(8)=params(5)*ys_(5);
    ys_(9)=ys_(2)^(-params(9))*(1-params(5)+ys_(11)*params(4)*(1-ys_(6))*ys_(5)^(params(4)-1)*ys_(3)^(1-params(4)));
    ys_(7)=ys_(3)^(1-params(4))*ys_(11)*ys_(5)^params(4);
    ys_(10)=ys_(7)/ys_(3);
    % Auxiliary equations
    check_=0;
end
